name: build script for GameLogic.c

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      
      - name: build GameLogic
        run: gcc -o GameLogic GameLogic.c 

      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: GameLogic
          path: ./GameLogic